services:
  db:
    image: mysql:8.0
    container_name: libreria_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: libreria_online
    ports:
      - "3306:3306"
    volumes:
      - libreria_mysql_data:/var/lib/mysql

volumes:
  libreria_mysql_data:
