import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const descriptions: Record<string, string> = {
  'Attack on Titan Vol. 1': 'La humanidad vive encerrada tras gigantescas murallas que la protegen de los Titanes, seres humanoides que devoran personas sin aparente razón. Eren Yeager sueña con explorar el mundo exterior, pero ese sueño se convierte en pesadilla cuando un Titán Colosal derriba la muralla de su ciudad. Tras perder a su madre, Eren jura exterminará a todos los Titanes y se alista en el Cuerpo de Exploración para descubrir el oscuro secreto que se esconde tras las murallas.',
  'One Piece Vol. 100': 'Monkey D. Luffy y su tripulación de Piratas del Sombrero de Paja continúan su épica travesía por los mares del mundo en busca del legendario tesoro conocido como One Piece. En este volumen especial número 100, la saga de Wano alcanza su punto más álgido en una batalla épica que pondrá a prueba los límites de Luffy y revelará el verdadero potencial de su Fruta del Diablo. Un hito en la historia del manga mundial.',
  'Naruto Vol. 1': 'Naruto Uzumaki es un joven ninja de la aldea oculta de la Hoja con un oscuro secreto: en su interior fue sellado el Zorro de Nueve Colas, el demonio que devastó la aldea hace doce años. Rechazado por sus vecinos, Naruto tiene un único objetivo: convertirse en Hokage, el líder ninja más poderoso de la aldea, para que todos le reconozcan y respeten. Su aventura comienza cuando supera contra todo pronóstico el examen de graduación de la academia ninja.',
  'Demon Slayer Vol. 1': 'Tanjiro Kamado llevaba una vida tranquila en las montañas cuidando de su familia hasta que un día regresó a casa para encontrar a todos sus seres queridos masacrados por un demonio. Solo sobrevivió su hermana Nezuko, pero convertida en demonio. Decidido a vengar a su familia y a encontrar la cura para Nezuko, Tanjiro se convierte en cazador de demonios. Un emotivo manga de acción sobre hermandad, sacrificio y determinación.',
  'My Hero Academia Vol. 1': 'En un mundo donde el ochenta por ciento de la humanidad posee superpoderes llamados Quirks, Izuku Midoriya nació sin ninguno. Aun así, sueña con convertirse en el mayor héroe del mundo. Todo cambia cuando conoce al héroe número uno, All Might, quien ve en él el espíritu de un verdadero héroe y decide transmitirle su poder legendario. Comienza así la historia de un chico sin talento que, gracias a su determinación, se labra su propio camino hacia la grandeza.',
  'El Señor de los Anillos': 'La obra cumbre de la fantasía épica moderna. Frodo Bolsón hereda el Anillo Único de su tío Bilbo, sin saber que es el arma definitiva forjada por el Señor Oscuro Sauron para dominar la Tierra Media. Con sus fieles amigos y una heterogénea Comunidad del Anillo, Frodo emprende un viaje hacia las oscuras tierras de Mordor para destruir el Anillo en el único lugar donde puede ser destruido: el Monte del Destino. Una aventura épica sobre amistad, sacrificio y la lucha del bien contra el mal.',
  'Harry Potter y la Piedra Filosofal': 'Harry Potter ha vivido toda su vida en el armario debajo de las escaleras de casa de sus tíos, sin saber que es un mago. Todo cambia el día de su undécimo cumpleaños, cuando recibe una carta de admisión al Colegio Hogwarts de Magia y Hechicería. En este mundo nuevo y mágico descubrirá que es famoso entre los magos, hará amigos para toda la vida y se enfrentará por primera vez a la oscura sombra del mago que intentó matarle de bebé: Lord Voldemort.',
  'Percy Jackson y el Ladrón del Rayo': 'Percy Jackson siempre ha tenido problemas en el colegio: es disléxico, hiperactivo y ha sido expulsado de seis colegios en seis años. Pero cuando una profesora se convierte en monstruo y le ataca, descubre que es hijo de un dios del Olimpo griego. Llevado al Campamento Mestizo, aprende que los dioses del Olimpo son muy reales y que el rayo maestro de Zeus ha sido robado. Percy tiene hasta el solsticio de verano para recuperarlo y evitar una guerra entre los dioses.',
  'Los Juegos del Hambre': 'En los escombros de lo que un día fue Norteamérica se alza Panem, una nación dividida en doce distritos que sirven a la opulenta Ciudad del Capitolio. Como castigo por una antigua rebelión, cada año el Capitolio organiza los Juegos del Hambre: dos jóvenes de cada distrito son elegidos por sorteo para luchar a muerte en una arena televisada en directo. Cuando su hermana pequeña es seleccionada, Katniss Everdeen se ofrece voluntaria en su lugar. Comienza así su lucha por la supervivencia y, sin proponérselo, por la libertad de todo un pueblo.',
  'Divergente': 'En una sociedad futura dividida en cinco facciones según la virtud predominante de cada persona, Beatrice Prior descubre en la ceremonia de elección que no pertenece a ninguna: es Divergente. Eligiendo la facción de Osadía bajo el nombre de Tris, descubrirá que ser Divergente es peligroso, que el gobierno la teme y que una conspiración amenaza con destruir la frágil paz entre las facciones. Una historia de identidad, valentía y amor en un mundo donde encajar puede costarte la vida.',
  'It': 'En la tranquila ciudad de Derry, Maine, los niños desaparecen cada veintisiete años devorados por una entidad maligna que adopta la forma de lo que más temes, aunque su apariencia favorita sea la de un payaso llamado Pennywise. Un grupo de siete amigos apodados el Club de los Perdedores se enfrenta a It durante su infancia y, décadas después, deberán volver para terminar lo que empezaron. La obra más aterradora de Stephen King es también su reflexión más profunda sobre la amistad, el miedo y la pérdida de la inocencia.',
  'El Resplandor': 'Jack Torrance, escritor con problemas de alcoholismo, acepta el trabajo de vigilante invernal del Hotel Overlook con la esperanza de encontrar la paz necesaria para terminar su novela. Se instala allí con su esposa Wendy y su hijo Danny, un niño con poderes psíquicos que le permiten ver el pasado violento del hotel. Conforme el invierno avanza y la nieve los aísla del mundo, el hotel comienza a ejercer su influencia maligna sobre Jack. Un estudio magistral del terror psicológico y la desintegración familiar.',
  'Frankenstein': 'Víctor Frankenstein, un brillante pero obsesivo estudiante de ciencias naturales, desafía los límites de lo posible y crea vida a partir de materia inerte. Pero la criatura que da vida es tan horrible que la rechaza de inmediato, sembrando las semillas de una tragedia inevitable. La criatura, dotada de inteligencia y sentimientos, busca desesperadamente el afecto que le es negado y acaba convirtiéndose en la pesadilla de su creador. La novela fundadora de la ciencia ficción es también una poderosa reflexión sobre la responsabilidad científica y la naturaleza humana.',
  'Drácula': 'El joven abogado Jonathan Harker viaja a Transilvania para completar una transacción inmobiliaria con el misterioso Conde Drácula. Una vez en el castillo, Harker comprende que es prisionero de un ser sobrenatural que planea trasladarse a Inglaterra. Lo que sigue es una carrera contra el tiempo en la que un grupo de hombres y mujeres, guiados por el profesor Van Helsing, intentará detener al Conde antes de que extienda su maldición por todo el mundo civilizado. La novela epistolar que definió para siempre la figura del vampiro.',
  'La Casa de los Espíritus': 'A través de cuatro generaciones de la familia Trueba, Isabel Allende teje una épica saga que mezcla lo real y lo mágico en un país latinoamericano que vive convulsionado por la política. Clara, dotada de poderes proféticos, Blanca, su hija rebelde, y Alba, su nieta comprometida con la revolución, encarnan la lucha de las mujeres por sobrevivir y resistir en un mundo dominado por hombres y marcado por la violencia política. Una novela de amor, magia y memoria histórica.',
  'Cien Años de Soledad': 'La historia de la familia Buendía a lo largo de siete generaciones en el pueblo mítico de Macondo, fundado en medio de la selva por José Arcadio Buendía. A través de este microcosmos García Márquez construye la historia de toda Latinoamérica, con sus guerras civiles, su colonialismo y sus pasiones desmedidas. La novela que definió el realismo mágico y que le valió el Premio Nobel a su autor es considerada la obra cumbre de las letras hispanoamericanas del siglo XX.',
  'Don Quijote de la Mancha': 'Alonso Quijano, un hidalgo manchego que ha perdido el juicio a fuerza de leer libros de caballerías, se cree caballero andante, toma el nombre de Don Quijote de la Mancha y sale al mundo en busca de aventuras acompañado de su fiel escudero Sancho Panza. Lo que sigue es un viaje inolvidable lleno de molinos tomados por gigantes, rebaños confundidos con ejércitos y ventas que se convierten en castillos. La primera novela moderna de la historia occidental es también una profunda reflexión sobre la realidad, la ilusión y la locura.',
  'La Sombra del Viento': 'Barcelona, 1945. Un niño llamado Daniel acompaña a su padre al misterioso Cementerio de los Libros Olvidados, donde elige un libro al azar: La Sombra del Viento, de Julián Carax. El libro le fascina, pero cuando intenta encontrar otras obras del autor descubre que alguien está destruyendo sistemáticamente todos los ejemplares de sus novelas. La búsqueda de la identidad de ese misterioso destructor de libros llevará a Daniel a desentrañar un oscuro secreto que atraviesa el tiempo y que tocará su propia vida de forma inesperada.',
  'El Nombre del Viento': 'Esta es la historia de Kvothe, el mago más legendario de su época, narrada de su propia voz. Desde sus humildes orígenes como hijo de una troupe de artistas ambulantes, pasando por su supervivencia en las calles de una gran ciudad y sus años en la Universidad de Magia, Kvothe relata cómo llegó a convertirse en el héroe y el villano que las leyendas describen. Una obra maestra de la fantasía épica que redefine el género con una prosa extraordinaria y una construcción del mundo sin parangón.',
  'Dune': 'El año 10191, el joven Paul Atreides llega al desértico planeta Arrakis, única fuente en el universo de la Especia, la sustancia más valiosa de la galaxia que permite los viajes espaciales. Cuando su familia es traicionada y destruida, Paul debe sobrevivir en el desierto con la ayuda de los Fremen, los habitantes nativos del planeta, y descubrir su propio destino como figura mesiánica. La novela de ciencia ficción más vendida de todos los tiempos es una épica meditación sobre el poder, la religión y la ecología.',
}

async function main() {
  const books = await prisma.book.findMany({ select: { id: true, title: true } })

  for (const book of books) {
    const description = descriptions[book.title]
    if (description) {
      await prisma.book.update({
        where: { id: book.id },
        data: { description },
      })
      console.log(`✓ ${book.title}`)
    } else {
      await prisma.book.update({
        where: { id: book.id },
        data: {
          description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.',
        },
      })
      console.log(`~ ${book.title} (Lorem ipsum)`)
    }
  }

  console.log('\nDescripciones actualizadas.')
}

main().catch(console.error).finally(() => prisma.$disconnect())
